export const SAVE_PRODUCTS = 'SAVE_PRODUCTS';
export const TOGGLE_CART = 'TOGGLE_CART';
export const TOGGLE_FAVORITES = 'TOGGLE_FAVORITES';

export const LOADING_PRODUCTS = 'LOADING_PRODUCTS';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const TOGGLE_CHECKOUT_MODAL = 'TOGGLE_MODAL_CHECKOUT';

export const UPDATE_ERRORS_DATA = 'UPDATE_ERRORS_DATA';
export const UPDATE_INPUT_VALUE = 'UPDATE_INPUT_VALUE';
export const UPDATE_TOUCHED_STATUS = 'UPDATE_TOUCHED_STATUS';
export const RESET_FORM_DATA = "RESET_FORM_DATA";
