export const SAVE_PRODUCTS = 'SAVE_PRODUCTS';
export const TOGGLE_CART = 'TOGGLE_CART';
export const TOGGLE_FAVORITES = 'TOGGLE_FAVORITES';

export const LOADING_PRODUCTS = 'LOADING_PRODUCTS';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
